image: Visual Studio 2022

platform:
  - x64
  - aarch64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node x64
  - git reset --hard HEAD
  - npm install
  - node --version

build_script:
  - npm run release

test: off

branches:
  only:
    - master
